/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include"STM32_F103x6.h"
#include"STM32_F103c6_GPIO_Driver.h"
#include"LCD.h"
#include"STM32_F103c6_EXTI_Driver.h"


uint32_t IRQ_Flag ;

void Clock_INIT(){
	RCC_AFIO_CLK_EN();
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void EXTI9_CallBack(void){
	IRQ_Flag = 1;
	LCD_SEND_STRING("IRQ EXTI9 Has Happened _|- ");
	delay_ms(250);
}



int main(void)
{
	Clock_INIT();
	LCD_INIT();
	LCD_clear_screen();

	//EXTI Initialization
	EXTI_Pinconfig_t PinCfg;
	PinCfg.EXTI_Pin = EXTI9PB9;
	PinCfg.IRQ_EN = EXTI_IRQ_EN;
	PinCfg.Trigger_Case = RISING;
	PinCfg.P_CallBack = EXTI9_CallBack;
	MCAL_EXTI_GPIO_INIT(&PinCfg);


	while(1){
		if(IRQ_Flag == 1)
		{
			LCD_clear_screen();
			IRQ_Flag = 0;
		}
	}
}








